### ISSUE TITLE
how do i manipulate my epub

### ISSUE THREAD

**Issue by blennerSilva** [mertakdut/EpubParser#28] opened 2017-10-31 17:54 UTC
Does this lib has the means to manipulate the epub..such as :font size changes  , and page manipulation like seek bar changing pages ? for android

**Comment by mertakdut** [comment] 2018-02-23 23:33
Duplicate of [issue-29](https://github.com/mertakdut/EpubParser/issues/29).

**Closed as completed by mertakdut** 2018-02-23 23:33 UTC
