### ISSUE TITLE
Click on table of contents Gives error

### ISSUE THREAD

**Issue by Redman1037** [mertakdut/EpubParser#13] opened 2016-10-20 12:58 UTC
how can i navigate to specified page on clicking from table of content , it gives me issue and ,when i unzip the epub file and like its location like this   webView.loadDataWithBaseURL(location, sectionContent, "text/html", "UTF-8", null);  it works but it loads full book again in vertical scrolling, not as sections.

how do i redirect to correct page index  ( bookSection = reader.readSection(pageIndex);  ) on clicking on item from table of contents?

**Comment by mertakdut** [comment] 2016-10-21 10:47
This library aims to reduce the memory consumption by avoid loading the whole content into memory. But in the future, I plan to add the needed implementation. Though, I guess it may require some time and more resource to find the link's position.

Currently internal links and navigating to a certain page is not available.

This issue is a duplicate of <a href="https://github.com/mertakdut/EpubParser/issues/10">Issue #10 - Skip to specified page</a>.

**Closed** 2016-10-24 07:06 UTC
